<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $letter->letter_type_label }} — {{ $letter->job_title }}</title>
    <style>
        @page { margin: 2cm; }
        body {
            font-family: Georgia, "Times New Roman", serif;
            font-size: 12pt;
            line-height: 1.7;
            color: #111;
        }
        p { margin: 0 0 1em; }
        .footer {
            position: fixed;
            bottom: -1cm;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9pt;
            color: #888;
        }
    </style>
</head>
<body>

{!! $letter->content !!}

{{--
<div class="footer">
    Generated by {{ config('app.name') }} on {{ $generatedAt }}
</div> 
--}}

</body>
</html>